---
- name: Add cgroup directives to boot command line config
  ansible.builtin.lineinfile:
    path: /boot/firmware/cmdline.txt
    regexp: '((.)+?)(\scgroup_\w+=\w+)*$'
    line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
    backrefs: true
  when: ( ansible_facts.architecture is search("aarch64") or ansible_facts.architecture is search("armv7l"))
  register: enable_cgroups

- name: Reboot node to apply cgroups
  ansible.builtin.reboot:
  when: (enable_cgroups.changed and ansible_facts.architecture is search("aarch64")) or
        (enable_cgroups.changed and ansible_facts.architecture is search("armv7l"))
