---
- name: Add helm repo https://charts.longhorn.io
  become: true
  become_user: kube
  kubernetes.core.helm_repository:
    name: longhorn
    repo_url: https://charts.longhorn.io

- name: Install longhorn/longhorn
  become: true
  become_user: kube
  kubernetes.core.helm:
    name: "longhorn"
    namespace: "{{ core_apps_namespace }}"
    chart_ref: longhorn/longhorn
    wait: true
