---
- name: Add helm repo https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
  become: true
  become_user: kube
  kubernetes.core.helm_repository:
    name: external-nfs-provisioner
    repo_url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
  when: install_nfs_provisioner == "true"

- name: Install external-nfs-provisioner/nfs-subdir-external-provisioner
  become: true
  become_user: kube
  kubernetes.core.helm:
    name: nfs-subdir-external-provisioner
    namespace: "{{ core_apps_namespace }}"
    chart_ref: external-nfs-provisioner/nfs-subdir-external-provisioner
    values:
      nfs:
        server: "{ nfs_provisioner_server }"
        path: "{{ nfs_provisioner_path }}"
  when: install_nfs_provisioner == "true"
