---
- name: Create Kube account for interacting with cluster
  become: true
  ansible.builtin.user:
    name: kube
    state: present
    shell: /bin/bash
    system: false
    createhome: true

- name: Initialize the cluster
  become: true
  ansible.builtin.shell: "kubeadm init --pod-network-cidr={{ k8s_cidr }} && touch /var/lib/provisioning/cluster_initialized.txt"
  args:
    creates: /var/lib/provisioning/cluster_initialized.txt

- name: Create .kube directory
  become: true
  become_user: kube
  ansible.builtin.file:
    path: $HOME/.kube
    state: directory
    mode: "0755"

- name: Copies admin.conf to user's kube config
  become: true
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/kube/.kube/config
    remote_src: true
    mode: "0600"
    owner: kube

- name: Install Flannel CNI
  become: true
  become_user: kube
  ansible.builtin.command: "kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/{{ flannel_version }}/Documentation/kube-flannel.yml"
  args:
    chdir: $HOME
  register: output
  changed_when: output.rc == 0

- name: Get the token for joining the worker nodes
  become: true
  ansible.builtin.command: kubeadm token create --print-join-command
  register: kubernetes_join_command
  changed_when: kubernetes_join_command.stdout_lines | length > 0

- name: Copy join command to local file.
  become: false
  delegate_to: localhost
  ansible.builtin.copy:
    content: "{{ kubernetes_join_command.stdout_lines[0] }}"
    dest: "/tmp/kubernetes_join_command"
    mode: "0777"
