---
- name: Sysctl apply
  ansible.builtin.command: sysctl --system
  register: output
  changed_when: output.rc == 0

- name: Containerd restart
  ansible.builtin.systemd:
    name: containerd
    enabled: true
    state: restarted
